name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Actualizado a v4
      - name: Checkout del código
        uses: actions/checkout@v4

      # Actualizado a v4
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Actualizado a v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Usamos una versión de Node más actual

      - name: Instalar dependencias
        run: npm install

      # Este paso asume que tienes una carpeta /android en tu proyecto (React Native)
      - name: Generar APK de prueba (Debug)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      # Actualizado a v4 (Aquí estaba el error principal)
      - name: Subir el APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk